/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.oodms.ui.UI_Admin;

import com.mycompany.oodms.Delivery;
import com.mycompany.oodms.DeliveryStaff;
import com.mycompany.oodms.OODMS_Main;
import com.mycompany.oodms.Services.DeliveryService;
import com.mycompany.oodms.Services.User.DeliveryStaffService;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mingl
 */
public class UI_Staff_Rating extends javax.swing.JPanel {

    /**
     * Creates new form UI_Staff_Rating
     */
    public UI_Staff_Rating() {
        initComponents();
        backBtn.setFont(new Font("MV Boli",Font.PLAIN,12));
        backBtn.setForeground(new Color(77, 77, 77, 124));
        backBtn.setBounds(68,70,45,11);
        backBtn.setBorder(BorderFactory.createEmptyBorder());
        backBtn.setFocusable(false);
        backBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        ArrayList<Delivery> deliveries = DeliveryService.getDeliveryService().getDeliveryForRating();
        ArrayList<DeliveryStaff> staffs = DeliveryStaffService.getDeliveryStaffService().getStaffs();
        
        DefaultTableModel model = (DefaultTableModel) staffTable.getModel();
        for(int i = 0; i < staffs.size(); i++){
            int numR1 = 0;
            int numR2 = 0;
            int numR3 = 0;
            int numR4 = 0;
            int numR5 = 0;

             for(int x = 0; x < deliveries.size(); x++){
                 if(deliveries.get(x).getStaff().getID() == staffs.get(i).getID()){
                    int rating = deliveries.get(x).getDeliveryRating();
                    switch(rating) {
                        case 1 -> {
                            numR1 += 1;
                        }
                        case 2 -> {
                            numR2 += 1;
                        }
                        case 3 -> {
                            numR3 += 1;
                        }
                        case 4 -> {
                            numR4 += 1;
                        }
                        case 5 -> {
                            numR5 += 1;
                        }
                    }
                 }
             }
             
             if(numR1 == 0 && numR2 == 0 && numR3 == 0 && numR4 == 0 && numR5 == 0){
                 continue;
             }
             
            model.addRow(new Object[staffs.size()]);
            model.setValueAt(staffs.get(i).getEmail(), i, 0);
            model.setValueAt(numR5, i, 1);
            model.setValueAt(numR4, i, 2);
            model.setValueAt(numR3, i, 3);
            model.setValueAt(numR2, i, 4);
            model.setValueAt(numR1, i, 5);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        salesReportLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1080, 768));
        setMinimumSize(new java.awt.Dimension(1080, 768));
        setPreferredSize(new java.awt.Dimension(1080, 768));

        backBtn.setText("< back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        salesReportLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        salesReportLabel1.setForeground(new java.awt.Color(0, 0, 0));
        salesReportLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesReportLabel1.setText("Staff Rating Report");

        staffTable.setBackground(new java.awt.Color(255, 255, 255));
        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StaffID", "No of 5 Star", "No of 4 Star", "No of 3 Star", "No of 2 Star", "No of 1 Star"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(staffTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(backBtn)
                .addGap(308, 308, 308)
                .addComponent(salesReportLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(salesReportLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(backBtn)))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        OODMS_Main.frame.replacePanel(new UI_Report());
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel salesReportLabel1;
    private javax.swing.JTable staffTable;
    // End of variables declaration//GEN-END:variables
}
